/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manejadora;

import Base_de_Datos.Busquedas;
import Base_de_Datos.Cliente;
import Base_de_Datos.Consultas;
import Base_de_Datos.Eliminar;
import Base_de_Datos.Ingresos;
import Base_de_Datos.conexionBD;
import java.sql.Connection;
//import static java.lang.String.valueOf;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gganp
 */
public class ASEGURADORA extends javax.swing.JInternalFrame {

    /**
     * Creates new form ASEGURADORA
     */
      Consultas consulta = new Consultas();
    Busquedas src = new Busquedas();
   public static int tipo=0;
    Eliminar del =new Eliminar();
    Cliente cl = new Cliente();
    conexionBD con = new conexionBD();
    Connection cn = con.conexion();
    public ASEGURADORA() {
        initComponents();
        IGM2IngresarPagTxt4.setEnabled(false);
         if(tipo==2){IGM2IngresarPagTxt12.setEnabled(false);
       IGM2IngresarPagTxt4.setEnabled(false);
       IGM2IngresarPagTxt5.setEnabled(false);
      
       }
        consulta.mostrar_tabla5();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_ingreso_cts12 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel168 = new javax.swing.JLabel();
        NOMBRE_AS = new javax.swing.JTextField();
        jLabel169 = new javax.swing.JLabel();
        NIT_AS = new javax.swing.JTextField();
        DIRECCION_AS = new javax.swing.JTextField();
        jLabel171 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        TEL_AS = new javax.swing.JTextArea();
        jLabel173 = new javax.swing.JLabel();
        IGM2IngresarPagTxt2 = new javax.swing.JButton();
        IGM2IngresarPagTxt3 = new javax.swing.JButton();
        IGM2IngresarPagTxt4 = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        TBL_AS = new javax.swing.JTable();
        IGM2IngresarPagTxt12 = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        TEL_AS1 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        TEL_AS2 = new javax.swing.JTextArea();
        jLabel172 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        IGM2IngresarPagTxt5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("ASEGURADORAS");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panel_ingreso_cts12.setBackground(new java.awt.Color(102, 0, 0));

        jLabel89.setBackground(new java.awt.Color(0, 0, 51));
        jLabel89.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("ASEGURADORAS");
        jLabel89.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel42.setBackground(new java.awt.Color(0, 0, 51));
        jPanel42.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel42.setOpaque(false);

        jLabel168.setBackground(new java.awt.Color(0, 0, 51));
        jLabel168.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel168.setForeground(new java.awt.Color(255, 255, 255));
        jLabel168.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel168.setText("NOMBRE");
        jLabel168.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        NOMBRE_AS.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        NOMBRE_AS.setForeground(new java.awt.Color(0, 0, 51));
        NOMBRE_AS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel169.setBackground(new java.awt.Color(0, 0, 51));
        jLabel169.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel169.setForeground(new java.awt.Color(255, 255, 255));
        jLabel169.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel169.setText("NIT");
        jLabel169.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        NIT_AS.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        NIT_AS.setForeground(new java.awt.Color(0, 0, 51));
        NIT_AS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DIRECCION_AS.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        DIRECCION_AS.setForeground(new java.awt.Color(0, 0, 51));
        DIRECCION_AS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel171.setBackground(new java.awt.Color(0, 0, 51));
        jLabel171.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel171.setForeground(new java.awt.Color(255, 255, 255));
        jLabel171.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel171.setText("DIRECCION");
        jLabel171.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TEL_AS.setColumns(20);
        TEL_AS.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        TEL_AS.setRows(5);
        jScrollPane18.setViewportView(TEL_AS);

        jLabel173.setBackground(new java.awt.Color(0, 0, 51));
        jLabel173.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel173.setForeground(new java.awt.Color(255, 255, 255));
        jLabel173.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel173.setText("TELEFONOS / EMAIL");
        jLabel173.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(jLabel173, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane18))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel168, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel169, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel171, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DIRECCION_AS)
                            .addComponent(NIT_AS)
                            .addComponent(NOMBRE_AS, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOMBRE_AS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel168, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIT_AS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel169, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DIRECCION_AS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel171, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel173, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        IGM2IngresarPagTxt2.setBackground(new java.awt.Color(0, 0, 0));
        IGM2IngresarPagTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        IGM2IngresarPagTxt2.setForeground(new java.awt.Color(255, 255, 255));
        IGM2IngresarPagTxt2.setText("LIMPIAR");
        IGM2IngresarPagTxt2.setBorder(null);
        IGM2IngresarPagTxt2.setBorderPainted(false);
        IGM2IngresarPagTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGM2IngresarPagTxt2limpiar18ActionPerformed(evt);
            }
        });

        IGM2IngresarPagTxt3.setBackground(new java.awt.Color(0, 0, 0));
        IGM2IngresarPagTxt3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        IGM2IngresarPagTxt3.setForeground(new java.awt.Color(255, 255, 255));
        IGM2IngresarPagTxt3.setText("GUARDAR");
        IGM2IngresarPagTxt3.setBorder(null);
        IGM2IngresarPagTxt3.setBorderPainted(false);
        IGM2IngresarPagTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGM2IngresarPagTxt3limpiar18ActionPerformed(evt);
            }
        });

        IGM2IngresarPagTxt4.setBackground(new java.awt.Color(0, 0, 0));
        IGM2IngresarPagTxt4.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        IGM2IngresarPagTxt4.setForeground(new java.awt.Color(255, 255, 255));
        IGM2IngresarPagTxt4.setText("ACTUALIZAR");
        IGM2IngresarPagTxt4.setBorder(null);
        IGM2IngresarPagTxt4.setBorderPainted(false);
        IGM2IngresarPagTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGM2IngresarPagTxt4limpiar18ActionPerformed(evt);
            }
        });

        TBL_AS.setBackground(new java.awt.Color(0, 0, 51));
        TBL_AS.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TBL_AS.setForeground(new java.awt.Color(255, 255, 255));
        TBL_AS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBL_AS.setAlignmentX(1.0F);
        TBL_AS.setAlignmentY(1.0F);
        TBL_AS.setRowHeight(30);
        TBL_AS.setSelectionBackground(new java.awt.Color(0, 153, 255));
        TBL_AS.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TBL_AS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ASMouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(TBL_AS);

        IGM2IngresarPagTxt12.setBackground(new java.awt.Color(0, 0, 0));
        IGM2IngresarPagTxt12.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        IGM2IngresarPagTxt12.setForeground(new java.awt.Color(255, 255, 255));
        IGM2IngresarPagTxt12.setText("MODIFICAR");
        IGM2IngresarPagTxt12.setBorder(null);
        IGM2IngresarPagTxt12.setBorderPainted(false);
        IGM2IngresarPagTxt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGM2IngresarPagTxt12limpiar18ActionPerformed(evt);
            }
        });

        TEL_AS1.setColumns(20);
        TEL_AS1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        TEL_AS1.setRows(5);
        jScrollPane21.setViewportView(TEL_AS1);

        TEL_AS2.setColumns(20);
        TEL_AS2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        TEL_AS2.setRows(5);
        jScrollPane22.setViewportView(TEL_AS2);

        jLabel172.setBackground(new java.awt.Color(0, 0, 51));
        jLabel172.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel172.setForeground(new java.awt.Color(255, 255, 255));
        jLabel172.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel172.setText("TELEFONOS / EMAIL");
        jLabel172.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel175.setBackground(new java.awt.Color(0, 0, 51));
        jLabel175.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel175.setForeground(new java.awt.Color(255, 255, 255));
        jLabel175.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel175.setText("DIRECCION");
        jLabel175.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        IGM2IngresarPagTxt5.setBackground(new java.awt.Color(0, 0, 0));
        IGM2IngresarPagTxt5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        IGM2IngresarPagTxt5.setForeground(new java.awt.Color(255, 255, 255));
        IGM2IngresarPagTxt5.setText("ELIMINAR");
        IGM2IngresarPagTxt5.setBorder(null);
        IGM2IngresarPagTxt5.setBorderPainted(false);
        IGM2IngresarPagTxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGM2IngresarPagTxt5limpiar18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ingreso_cts12Layout = new javax.swing.GroupLayout(panel_ingreso_cts12);
        panel_ingreso_cts12.setLayout(panel_ingreso_cts12Layout);
        panel_ingreso_cts12Layout.setHorizontalGroup(
            panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ingreso_cts12Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_ingreso_cts12Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel172, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel175, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_ingreso_cts12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IGM2IngresarPagTxt4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IGM2IngresarPagTxt12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IGM2IngresarPagTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IGM2IngresarPagTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IGM2IngresarPagTxt5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(190, 190, 190)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panel_ingreso_cts12Layout.setVerticalGroup(
            panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ingreso_cts12Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_ingreso_cts12Layout.createSequentialGroup()
                        .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_ingreso_cts12Layout.createSequentialGroup()
                        .addComponent(IGM2IngresarPagTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IGM2IngresarPagTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IGM2IngresarPagTxt12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IGM2IngresarPagTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(IGM2IngresarPagTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel172, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panel_ingreso_cts12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_ingreso_cts12Layout.createSequentialGroup()
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel175, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ingreso_cts12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_ingreso_cts12, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IGM2IngresarPagTxt2limpiar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGM2IngresarPagTxt2limpiar18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IGM2IngresarPagTxt2limpiar18ActionPerformed

    private void IGM2IngresarPagTxt3limpiar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGM2IngresarPagTxt3limpiar18ActionPerformed
        Ingresos contacto =  new Ingresos();
        contacto.IngresosAseguradora();
        consulta.mostrar_tabla5();
        NOMBRE_AS.setText("");
        NIT_AS.setText("");
        TEL_AS.setText("");
        DIRECCION_AS.setText("");
    }//GEN-LAST:event_IGM2IngresarPagTxt3limpiar18ActionPerformed

    private void IGM2IngresarPagTxt4limpiar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGM2IngresarPagTxt4limpiar18ActionPerformed
        try {
            String id = TBL_AS.getValueAt(TBL_AS.getSelectedRow(),0).toString();
            String sql = "UPDATE tbl_aseguradora SET Nombre_as='"+NOMBRE_AS.getText()
            +"',Nit_as='"+NIT_AS.getText()+"',Direccion_as='"+DIRECCION_AS.getText()+"',Telefonos_as='"+TEL_AS.getText()+"' WHERE IdAseguradora='"+id+"'";

            PreparedStatement pps = cn.prepareStatement(sql);
            pps.executeUpdate();

            consulta.mostrar_tabla5();
            NOMBRE_AS.setText("");
            NIT_AS.setText("");
            TEL_AS.setText("");
            DIRECCION_AS.setText("");
             IGM2IngresarPagTxt4.setEnabled(false);
             IGM2IngresarPagTxt3.setEnabled(true);
            JOptionPane.showMessageDialog(null,"ACTUALIZADO");
        } catch (SQLException ex) {
            Logger.getLogger(PRINCIPAL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IGM2IngresarPagTxt4limpiar18ActionPerformed

    private void TBL_ASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ASMouseClicked
        consulta.mostrar_textfield5(TBL_AS.getValueAt(TBL_AS.getSelectedRow(),0).toString());
    }//GEN-LAST:event_TBL_ASMouseClicked

    private void IGM2IngresarPagTxt12limpiar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGM2IngresarPagTxt12limpiar18ActionPerformed
        int fila= TBL_AS.getSelectedRow();
        if(fila>=0){
            IGM2IngresarPagTxt4.setEnabled(true);
            IGM2IngresarPagTxt3.setEnabled(false);
            NOMBRE_AS.setText(TBL_AS.getValueAt(fila,1).toString());
            NIT_AS.setText(TBL_AS.getValueAt(fila,2).toString());
            DIRECCION_AS.setText(TEL_AS2.getText());
            TEL_AS.setText(TEL_AS1.getText());
        }else{ JOptionPane.showMessageDialog(null,"SELECCIONE UN REGISTRO");}
    }//GEN-LAST:event_IGM2IngresarPagTxt12limpiar18ActionPerformed

    private void IGM2IngresarPagTxt5limpiar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGM2IngresarPagTxt5limpiar18ActionPerformed
        int fila= TBL_AS.getSelectedRow();
        if(fila>=0){
            String sql = "DELETE  FROM tbl_aseguradora WHERE IdAseguradora ="+TBL_AS.getValueAt(fila,0).toString()+"";
            try {
                PreparedStatement pps = cn.prepareStatement(sql);
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null,"CONTACTO ELIMINADO");

                consulta.mostrar_tabla5();
                NOMBRE_AS.setText("");
                NIT_AS.setText("");
                DIRECCION_AS.setText("");
                TEL_AS.setText("");
                TEL_AS1.setText("");
                TEL_AS2.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(PRINCIPAL.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{ JOptionPane.showMessageDialog(null,"SELECCIONE UN REGISTRO");}
    }//GEN-LAST:event_IGM2IngresarPagTxt5limpiar18ActionPerformed

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
       this.setSize(1040, 857);
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
         this.setSize(200,40);
    }//GEN-LAST:event_formInternalFrameIconified


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField DIRECCION_AS;
    private javax.swing.JButton IGM2IngresarPagTxt12;
    private javax.swing.JButton IGM2IngresarPagTxt2;
    private javax.swing.JButton IGM2IngresarPagTxt3;
    private javax.swing.JButton IGM2IngresarPagTxt4;
    private javax.swing.JButton IGM2IngresarPagTxt5;
    public static javax.swing.JTextField NIT_AS;
    public static javax.swing.JTextField NOMBRE_AS;
    public static javax.swing.JTable TBL_AS;
    public static javax.swing.JTextArea TEL_AS;
    public static javax.swing.JTextArea TEL_AS1;
    public static javax.swing.JTextArea TEL_AS2;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JPanel panel_ingreso_cts12;
    // End of variables declaration//GEN-END:variables
}
