/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manejadora;

import Base_de_Datos.Busquedas;
import Base_de_Datos.Cliente;
import Base_de_Datos.Consultas;
import Base_de_Datos.Eliminar;
import static java.lang.String.valueOf;
import Base_de_Datos.Ingresos;
import Base_de_Datos.conexionBD;
import Codigos_de_Barras.Id_Cod;
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gganp
 */
public class CLIENTES extends javax.swing.JInternalFrame {

    /**
     * Creates new form CLIENTES
     */
    public static int tipo=0;
    public CLIENTES() {
        
        initComponents();
        
       CLIENTES.setEnabled(false);
        
        
      ICAceptarBtn5.setEnabled(false);
        if(tipo==2){ModificacionMenu2Btn.setEnabled(false);
       EliminarMenu2Btn.setEnabled(false);
       CcltModificarBtn.setEnabled(false);
       CcltEliminarBtn.setEnabled(false);
       }
       consulta.mostrar_tabla1();
       Cclt1ComboBox.addItem("Id");
       Cclt1ComboBox.addItem("1er.Nombre");
       Cclt1ComboBox.addItem("2do.Nombre");
       Cclt1ComboBox.addItem("3er.Nombre");
       Cclt1ComboBox.addItem("1er.Apellido");
       Cclt1ComboBox.addItem("2do.Apellido");
       
       ICComboBox3.addItem("Soltero");
       ICComboBox3.addItem("Casado");
       ICComboBox3.addItem("Viudo");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CLIENTES = new javax.swing.JTabbedPane();
        MENU2 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        IngresosMenu2Btn = new javax.swing.JButton();
        EliminarMenu2Btn = new javax.swing.JButton();
        ConsultaMenu2Btn = new javax.swing.JButton();
        ModificacionMenu2Btn = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        I_CLIENTES2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        ICApellido1Txt2 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        ICApellidoCasTxt2 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        ICNombre1Txt2 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        ICNombre2Txt2 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        ICNombre3Txt2 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        ICNoDpiTxt2 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        ICFNacTxt2 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        ICEdadTxt2 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        ICProfesionTxt2 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        ICDirDomTxt2 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        ICDirCobroTxt2 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        ICNitTxt2 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        ICTelefonoCasTxt2 = new javax.swing.JTextField();
        ICTelOficinaTxt2 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        ICTelCelTxt2 = new javax.swing.JTextField();
        ICAceptarBtn4 = new javax.swing.JButton();
        ICLimpiarbtn2 = new javax.swing.JButton();
        ICAceptarBtn5 = new javax.swing.JButton();
        ICComboBox3 = new javax.swing.JComboBox<>();
        ICSalirBtn = new javax.swing.JButton();
        C_CLIENTES1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Cclt1ComboBox = new javax.swing.JComboBox<>();
        Cclt1BusquedaTxt = new javax.swing.JTextField();
        CcltLimpiarBtn = new javax.swing.JButton();
        CcltBuscarBtn = new javax.swing.JButton();
        CcltSalirBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblCC1 = new javax.swing.JTable();
        C_CLIENTES2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Cclt2SalirBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblCC2 = new javax.swing.JTable();
        CcltEliminarBtn = new javax.swing.JButton();
        CcltModificarBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("CLIENTES");
        setFrameIcon(null);
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(1517, 895));
        setMinimumSize(new java.awt.Dimension(200, 50));
        setPreferredSize(new java.awt.Dimension(1515, 948));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        MENU2.setBackground(new java.awt.Color(0, 51, 51));

        jPanel25.setBackground(new java.awt.Color(0, 0, 0));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel25.setOpaque(false);

        IngresosMenu2Btn.setBackground(new java.awt.Color(0, 0, 0));
        IngresosMenu2Btn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        IngresosMenu2Btn.setForeground(new java.awt.Color(255, 255, 255));
        IngresosMenu2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/disquete (2).png"))); // NOI18N
        IngresosMenu2Btn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        IngresosMenu2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresosMenu2BtnActionPerformed(evt);
            }
        });

        EliminarMenu2Btn.setBackground(new java.awt.Color(0, 0, 0));
        EliminarMenu2Btn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        EliminarMenu2Btn.setForeground(new java.awt.Color(255, 255, 255));
        EliminarMenu2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/boton-eliminar.png"))); // NOI18N
        EliminarMenu2Btn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        EliminarMenu2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMenu2BtnActionPerformed(evt);
            }
        });

        ConsultaMenu2Btn.setBackground(new java.awt.Color(0, 0, 0));
        ConsultaMenu2Btn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ConsultaMenu2Btn.setForeground(new java.awt.Color(255, 255, 255));
        ConsultaMenu2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/enfocar (2).png"))); // NOI18N
        ConsultaMenu2Btn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ConsultaMenu2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMenu2BtnActionPerformed(evt);
            }
        });

        ModificacionMenu2Btn.setBackground(new java.awt.Color(0, 0, 0));
        ModificacionMenu2Btn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ModificacionMenu2Btn.setForeground(new java.awt.Color(255, 255, 255));
        ModificacionMenu2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/goma-de-borrar.png"))); // NOI18N
        ModificacionMenu2Btn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ModificacionMenu2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificacionMenu2BtnActionPerformed(evt);
            }
        });

        jLabel75.setBackground(new java.awt.Color(0, 0, 51));
        jLabel75.setFont(new java.awt.Font("Segoe UI Historic", 1, 32)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("INGRESO");
        jLabel75.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel76.setBackground(new java.awt.Color(0, 0, 51));
        jLabel76.setFont(new java.awt.Font("Segoe UI Historic", 1, 32)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("ELIMINACION");
        jLabel76.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel77.setBackground(new java.awt.Color(0, 0, 51));
        jLabel77.setFont(new java.awt.Font("Segoe UI Historic", 1, 28)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setText("MODIFICACION");
        jLabel77.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel78.setBackground(new java.awt.Color(0, 0, 51));
        jLabel78.setFont(new java.awt.Font("Segoe UI Historic", 1, 32)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("CONSULTA");
        jLabel78.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IngresosMenu2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConsultaMenu2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ModificacionMenu2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EliminarMenu2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(EliminarMenu2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultaMenu2Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(IngresosMenu2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ModificacionMenu2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jLabel79.setBackground(new java.awt.Color(0, 0, 51));
        jLabel79.setFont(new java.awt.Font("Segoe UI Historic", 1, 40)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("CLIENTES");
        jLabel79.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout MENU2Layout = new javax.swing.GroupLayout(MENU2);
        MENU2.setLayout(MENU2Layout);
        MENU2Layout.setHorizontalGroup(
            MENU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENU2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MENU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENU2Layout.createSequentialGroup()
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(697, 697, 697))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENU2Layout.createSequentialGroup()
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))))
        );
        MENU2Layout.setVerticalGroup(
            MENU2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENU2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        CLIENTES.addTab("MENU", MENU2);

        I_CLIENTES2.setBackground(new java.awt.Color(0, 51, 51));
        I_CLIENTES2.setMaximumSize(new java.awt.Dimension(1517, 895));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INGRESO CLIENTES");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel11.setBackground(new java.awt.Color(0, 0, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel11.setOpaque(false);

        jLabel55.setBackground(new java.awt.Color(0, 0, 51));
        jLabel55.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("1er. APELLIDO");
        jLabel55.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICApellido1Txt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICApellido1Txt2.setForeground(new java.awt.Color(0, 0, 51));
        ICApellido1Txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel56.setBackground(new java.awt.Color(0, 0, 51));
        jLabel56.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("2do. APELLIDO");
        jLabel56.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICApellido2Txt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICApellido2Txt2.setForeground(new java.awt.Color(0, 0, 51));
        ICApellido2Txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel57.setBackground(new java.awt.Color(0, 0, 51));
        jLabel57.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("APELLIDO DE CASADA");
        jLabel57.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICApellidoCasTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICApellidoCasTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICApellidoCasTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel58.setBackground(new java.awt.Color(0, 0, 51));
        jLabel58.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("1er. NOMBRE");
        jLabel58.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICNombre1Txt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICNombre1Txt2.setForeground(new java.awt.Color(0, 0, 51));
        ICNombre1Txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel59.setBackground(new java.awt.Color(0, 0, 51));
        jLabel59.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("2do. NOMBRE");
        jLabel59.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICNombre2Txt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICNombre2Txt2.setForeground(new java.awt.Color(0, 0, 51));
        ICNombre2Txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel60.setBackground(new java.awt.Color(0, 0, 51));
        jLabel60.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("3er. NOMBRE");
        jLabel60.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICNombre3Txt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICNombre3Txt2.setForeground(new java.awt.Color(0, 0, 51));
        ICNombre3Txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel61.setBackground(new java.awt.Color(0, 0, 51));
        jLabel61.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("No. DE DPI");
        jLabel61.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICNoDpiTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICNoDpiTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICNoDpiTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ICNoDpiTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICNoDpiTxt2ActionPerformed(evt);
            }
        });

        jLabel62.setBackground(new java.awt.Color(0, 0, 51));
        jLabel62.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("FECHA NACIMIENTO");
        jLabel62.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICFNacTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICFNacTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICFNacTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel63.setBackground(new java.awt.Color(0, 0, 51));
        jLabel63.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("EDAD");
        jLabel63.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICEdadTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICEdadTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICEdadTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel64.setBackground(new java.awt.Color(0, 0, 51));
        jLabel64.setFont(new java.awt.Font("Segoe UI Historic", 1, 17)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("PROFESION u OFICIO");
        jLabel64.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICProfesionTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICProfesionTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICProfesionTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel65.setBackground(new java.awt.Color(0, 0, 51));
        jLabel65.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("ESTADO CIVIL");
        jLabel65.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel66.setBackground(new java.awt.Color(0, 0, 51));
        jLabel66.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("DIR. DOMICILIO");
        jLabel66.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICDirDomTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICDirDomTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICDirDomTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel67.setBackground(new java.awt.Color(0, 0, 51));
        jLabel67.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("DIR. COBRO");
        jLabel67.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICDirCobroTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICDirCobroTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICDirCobroTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel68.setBackground(new java.awt.Color(0, 0, 51));
        jLabel68.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("NIT");
        jLabel68.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICNitTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICNitTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICNitTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel69.setBackground(new java.awt.Color(0, 0, 51));
        jLabel69.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("TELEFONO DE CASA");
        jLabel69.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICTelefonoCasTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICTelefonoCasTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICTelefonoCasTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ICTelOficinaTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICTelOficinaTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICTelOficinaTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel70.setBackground(new java.awt.Color(0, 0, 51));
        jLabel70.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("TELEFONO OFICINA");
        jLabel70.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel71.setBackground(new java.awt.Color(0, 0, 51));
        jLabel71.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("TELEFONO CELULAR");
        jLabel71.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ICTelCelTxt2.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        ICTelCelTxt2.setForeground(new java.awt.Color(0, 0, 51));
        ICTelCelTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ICAceptarBtn4.setBackground(new java.awt.Color(0, 0, 0));
        ICAceptarBtn4.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ICAceptarBtn4.setForeground(new java.awt.Color(255, 255, 255));
        ICAceptarBtn4.setText("ACEPTAR");
        ICAceptarBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICAceptarBtnActionPerformed(evt);
            }
        });

        ICLimpiarbtn2.setBackground(new java.awt.Color(0, 0, 0));
        ICLimpiarbtn2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ICLimpiarbtn2.setForeground(new java.awt.Color(255, 255, 255));
        ICLimpiarbtn2.setText("LIMPIAR");
        ICLimpiarbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICLimpiarbtnActionPerformed(evt);
            }
        });

        ICAceptarBtn5.setBackground(new java.awt.Color(0, 0, 0));
        ICAceptarBtn5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ICAceptarBtn5.setForeground(new java.awt.Color(255, 255, 255));
        ICAceptarBtn5.setText("ACTUALIZAR");
        ICAceptarBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICAceptarBtn1ActionPerformed(evt);
            }
        });

        ICComboBox3.setBackground(new java.awt.Color(0, 0, 0));
        ICComboBox3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ICComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ICApellido1Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICApellido2Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICApellidoCasTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICNombre1Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ICNombre2Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICNombre3Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ICDirDomTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICDirCobroTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICNitTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICTelefonoCasTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ICTelOficinaTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICTelCelTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ICComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ICNoDpiTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICFNacTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICEdadTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICProfesionTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(ICAceptarBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(ICLimpiarbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ICAceptarBtn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(ICApellido1Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICApellido2Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICApellidoCasTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICNombre1Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(ICNombre2Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICNombre3Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(ICDirDomTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICDirCobroTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICNitTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICTelefonoCasTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(ICTelOficinaTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICTelCelTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ICAceptarBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ICLimpiarbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ICAceptarBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ICNoDpiTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(ICFNacTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICEdadTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICProfesionTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ICSalirBtn.setBackground(new java.awt.Color(51, 0, 0));
        ICSalirBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ICSalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        ICSalirBtn.setText("ATRAS");
        ICSalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICSalirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout I_CLIENTES2Layout = new javax.swing.GroupLayout(I_CLIENTES2);
        I_CLIENTES2.setLayout(I_CLIENTES2Layout);
        I_CLIENTES2Layout.setHorizontalGroup(
            I_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_CLIENTES2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(I_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(I_CLIENTES2Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ICSalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        I_CLIENTES2Layout.setVerticalGroup(
            I_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_CLIENTES2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(I_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(I_CLIENTES2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(ICSalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        CLIENTES.addTab("I. CLIENTES", I_CLIENTES2);

        C_CLIENTES1.setBackground(new java.awt.Color(0, 51, 51));
        C_CLIENTES1.setMaximumSize(new java.awt.Dimension(1517, 895));
        C_CLIENTES1.setPreferredSize(new java.awt.Dimension(1517, 895));

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONSULTA CLIENTES");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Cclt1ComboBox.setBackground(new java.awt.Color(0, 0, 0));
        Cclt1ComboBox.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Cclt1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cclt1ComboBoxActionPerformed(evt);
            }
        });

        Cclt1BusquedaTxt.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        Cclt1BusquedaTxt.setForeground(new java.awt.Color(0, 0, 51));
        Cclt1BusquedaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cclt1BusquedaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cclt1BusquedaTxtActionPerformed(evt);
            }
        });

        CcltLimpiarBtn.setBackground(new java.awt.Color(0, 0, 0));
        CcltLimpiarBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        CcltLimpiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        CcltLimpiarBtn.setText("LIMPIAR");
        CcltLimpiarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcltLimpiarBtnActionPerformed(evt);
            }
        });

        CcltBuscarBtn.setBackground(new java.awt.Color(0, 0, 0));
        CcltBuscarBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        CcltBuscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        CcltBuscarBtn.setText("BUSCAR ");
        CcltBuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcltBuscarBtnActionPerformed(evt);
            }
        });

        CcltSalirBtn.setBackground(new java.awt.Color(51, 0, 0));
        CcltSalirBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        CcltSalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        CcltSalirBtn.setText("ATRAS");
        CcltSalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcltSalirBtnActionPerformed(evt);
            }
        });

        TblCC1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TblCC1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblCC1.setAlignmentX(1.0F);
        TblCC1.setAlignmentY(1.0F);
        TblCC1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TblCC1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblCC1.setFillsViewportHeight(true);
        TblCC1.setName(""); // NOI18N
        TblCC1.setOpaque(false);
        TblCC1.setRequestFocusEnabled(false);
        TblCC1.setRowHeight(30);
        TblCC1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TblCC1.getTableHeader().setReorderingAllowed(false);
        TblCC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblCC1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblCC1);

        javax.swing.GroupLayout C_CLIENTES1Layout = new javax.swing.GroupLayout(C_CLIENTES1);
        C_CLIENTES1.setLayout(C_CLIENTES1Layout);
        C_CLIENTES1Layout.setHorizontalGroup(
            C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, C_CLIENTES1Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374)
                .addComponent(CcltSalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(C_CLIENTES1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(C_CLIENTES1Layout.createSequentialGroup()
                        .addGroup(C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cclt1BusquedaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CcltBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cclt1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CcltLimpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        C_CLIENTES1Layout.setVerticalGroup(
            C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(C_CLIENTES1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(C_CLIENTES1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(CcltSalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(C_CLIENTES1Layout.createSequentialGroup()
                        .addGroup(C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cclt1BusquedaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cclt1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(C_CLIENTES1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CcltLimpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CcltBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(141, 141, 141))
        );

        CLIENTES.addTab("C. CLIENTES 1", C_CLIENTES1);

        C_CLIENTES2.setBackground(new java.awt.Color(0, 51, 51));
        C_CLIENTES2.setMaximumSize(new java.awt.Dimension(1517, 895));

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CONSULTA CLIENTES");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Cclt2SalirBtn.setBackground(new java.awt.Color(51, 0, 0));
        Cclt2SalirBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Cclt2SalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        Cclt2SalirBtn.setText("ATRAS");
        Cclt2SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cclt2SalirBtnActionPerformed(evt);
            }
        });

        TblCC2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TblCC2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblCC2.setAlignmentX(1.0F);
        TblCC2.setAlignmentY(1.0F);
        TblCC2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TblCC2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblCC2.setFillsViewportHeight(true);
        TblCC2.setName(""); // NOI18N
        TblCC2.setOpaque(false);
        TblCC2.setRequestFocusEnabled(false);
        TblCC2.setRowHeight(30);
        TblCC2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TblCC2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TblCC2);

        CcltEliminarBtn.setBackground(new java.awt.Color(0, 0, 0));
        CcltEliminarBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        CcltEliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        CcltEliminarBtn.setText("ELIMINAR CLIENTE");
        CcltEliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcltEliminarBtnActionPerformed(evt);
            }
        });

        CcltModificarBtn.setBackground(new java.awt.Color(0, 0, 0));
        CcltModificarBtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        CcltModificarBtn.setForeground(new java.awt.Color(255, 255, 255));
        CcltModificarBtn.setText("MODIFICAR");
        CcltModificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcltModificarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout C_CLIENTES2Layout = new javax.swing.GroupLayout(C_CLIENTES2);
        C_CLIENTES2.setLayout(C_CLIENTES2Layout);
        C_CLIENTES2Layout.setHorizontalGroup(
            C_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, C_CLIENTES2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(C_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(C_CLIENTES2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(Cclt2SalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))
                    .addGroup(C_CLIENTES2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(C_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CcltModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CcltEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        C_CLIENTES2Layout.setVerticalGroup(
            C_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(C_CLIENTES2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(C_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(C_CLIENTES2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Cclt2SalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(C_CLIENTES2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(C_CLIENTES2Layout.createSequentialGroup()
                            .addComponent(CcltModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(104, 104, 104)
                            .addComponent(CcltEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(C_CLIENTES2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(148, 148, 148)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        CLIENTES.addTab("C. CLIENTES 2", C_CLIENTES2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CLIENTES, javax.swing.GroupLayout.PREFERRED_SIZE, 1491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CLIENTES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CcltModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcltModificarBtnActionPerformed

        
        if(tipo == 2){
         CcltModificarBtn.setEnabled(false);
         CcltEliminarBtn.setEnabled(false);
        }
        ICAceptarBtn5.setEnabled(true);
        ICApellido1Txt2.setText(valueOf(TblCC2.getValueAt(1, 1)));
        ICApellido2Txt2.setText(valueOf(TblCC2.getValueAt(2, 1)));
        ICApellidoCasTxt2.setText(valueOf(TblCC2.getValueAt(3, 1)));
        ICNombre1Txt2.setText(valueOf(TblCC2.getValueAt(4, 1)));
        ICNombre2Txt2.setText(valueOf(TblCC2.getValueAt(5, 1)));
        ICNombre3Txt2.setText(valueOf(TblCC2.getValueAt(6, 1)));
        ICComboBox3.setSelectedItem(valueOf(TblCC2.getValueAt(7, 1))); 
        ICNoDpiTxt2.setText(valueOf(TblCC2.getValueAt(8, 1)));
        ICFNacTxt2.setText(valueOf(TblCC2.getValueAt(9, 1)));
        ICEdadTxt2.setText(valueOf(TblCC2.getValueAt(10, 1)));
        ICProfesionTxt2.setText(valueOf(TblCC2.getValueAt(11, 1)));
        ICDirDomTxt2.setText(valueOf(TblCC2.getValueAt(12, 1)));
        ICDirCobroTxt2.setText(valueOf(TblCC2.getValueAt(13, 1)));
        ICNitTxt2.setText(valueOf(TblCC2.getValueAt(14, 1)));
        ICTelefonoCasTxt2.setText(valueOf(TblCC2.getValueAt(15, 1)));
        ICTelOficinaTxt2.setText(valueOf(TblCC2.getValueAt(16, 1)));
        ICTelCelTxt2.setText(valueOf(TblCC2.getValueAt(17, 1)));
         ICAceptarBtn5.setEnabled(true);
         ICAceptarBtn4.setEnabled(false);
         
        CLIENTES.setSelectedIndex(1);
    }//GEN-LAST:event_CcltModificarBtnActionPerformed

    private void CcltEliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcltEliminarBtnActionPerformed
        del.Eliminar_Cliente(TblCC2.getValueAt(0,1).toString());
        CLIENTES.setSelectedIndex(1);
        consulta.mostrar_tabla1();
    }//GEN-LAST:event_CcltEliminarBtnActionPerformed

    private void Cclt2SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cclt2SalirBtnActionPerformed
       CLIENTES.setSelectedIndex(2);
    }//GEN-LAST:event_Cclt2SalirBtnActionPerformed

    private void TblCC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblCC1MouseClicked
        int fila  = TblCC1.getSelectedRow();String Id;
        if (fila>=0){
            Id = valueOf(TblCC1.getValueAt(fila, 0));
            
            consulta.cc2(Id);
            CLIENTES.setSelectedIndex(3);

    }//GEN-LAST:event_TblCC1MouseClicked
    }
    private void CcltSalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcltSalirBtnActionPerformed
      CLIENTES.setSelectedIndex(0);
    }//GEN-LAST:event_CcltSalirBtnActionPerformed

    private void CcltBuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcltBuscarBtnActionPerformed
        String campo = Cclt1ComboBox.getSelectedItem().toString();

        src.Buscar1(src.Campo2(campo),Cclt1BusquedaTxt.getText());
    }//GEN-LAST:event_CcltBuscarBtnActionPerformed

    private void CcltLimpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcltLimpiarBtnActionPerformed
       Cclt1BusquedaTxt.setText(""); consulta.mostrar_tabla1();
    }//GEN-LAST:event_CcltLimpiarBtnActionPerformed

    private void Cclt1BusquedaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cclt1BusquedaTxtActionPerformed

    }//GEN-LAST:event_Cclt1BusquedaTxtActionPerformed

    private void Cclt1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cclt1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cclt1ComboBoxActionPerformed

    private void ICSalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICSalirBtnActionPerformed
       CLIENTES.setSelectedIndex(0);
    }//GEN-LAST:event_ICSalirBtnActionPerformed

    private void ICComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ICComboBox1ActionPerformed

    private void ICAceptarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICAceptarBtn1ActionPerformed
        //MODIFICACION
          if(ICNombre1Txt2.getText().equals("") || ICApellido1Txt2.getText().equals("") || ICFNacTxt2.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor rellene los siguientes campos:\n- 1er. Nombre.\n- 1er Apellido.\n- Fecha de nacimiento.");
        }else{
        try {
           String id = valueOf(TblCC2.getValueAt(0, 1));
            String sql = "UPDATE tbl_clientes SET Apellido1_clt='"+ICApellido1Txt2.getText()+"',Apellido2_clt='"+ICApellido2Txt2.getText()+"',ApellidoCasada_clt='"
                   +ICApellidoCasTxt2.getText()+"',Nombre1_clt='"+ICNombre1Txt2.getText()+"',Nombre2_clt='"+ICNombre2Txt2.getText()+"',Nombre3_clt='"+ICNombre3Txt2.getText()
                    +"',EstadoCivil_clt='"+ICComboBox3.getSelectedItem().toString()+"',Dpi_clt='"+ICNoDpiTxt2.getText()+"',FechaNac_clt='"+ICFNacTxt2.getText()+"',Edad_clt='"+ICEdadTxt2.getText()
                    +"',Profesion_clt='"+ICProfesionTxt2.getText()+"',DirDomicilio_clt='"+ICDirDomTxt2.getText()+"',DirCobro_clt='"+ICDirCobroTxt2.getText()
                    +"',Nit_clt='"+ICNitTxt2.getText()+"',TelCasa_clt='"+ICTelefonoCasTxt2.getText()+"',TelOficina_clt='"+ICTelOficinaTxt2.getText()
                    +"',TelCelular_clt='"+ICTelCelTxt2.getText()+"'WHERE IdCliente="+id+"";
            
            PreparedStatement pps = cn.prepareStatement(sql);
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null,"ACTUALIZADO");
        } catch (SQLException ex) {
            Logger.getLogger(PRINCIPAL.class.getName()).log(Level.SEVERE, null, ex);
        }}
      consulta.mostrar_tabla1();
     ICApellido1Txt2.setText("");
      ICApellido2Txt2.setText("");
      ICApellidoCasTxt2.setText("");
      ICNombre1Txt2.setText("");
      ICNombre2Txt2.setText("");
      ICNombre3Txt2.setText("");
      ICNoDpiTxt2.setText("");
      ICFNacTxt2.setText("");
      ICEdadTxt2.setText("");
      ICProfesionTxt2.setText("");
      ICDirDomTxt2.setText("");
      ICDirCobroTxt2.setText("");
      ICNitTxt2.setText("");
      ICTelefonoCasTxt2.setText("");
      ICTelOficinaTxt2.setText("");
      ICTelCelTxt2.setText("");
      consulta.cc2(valueOf(TblCC2.getValueAt(0, 1)));
        CLIENTES.setSelectedIndex(3);
    }//GEN-LAST:event_ICAceptarBtn1ActionPerformed

    private void ICLimpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICLimpiarbtnActionPerformed
       ICApellido1Txt2.setText("");
        ICApellido2Txt2.setText("");
        ICApellidoCasTxt2.setText("");
        ICNombre1Txt2.setText("");
        ICNombre2Txt2.setText("");
        ICNombre3Txt2.setText("");
        ICNoDpiTxt2.setText("");
        ICFNacTxt2.setText("");
        ICEdadTxt2.setText("");
        ICProfesionTxt2.setText("");
        ICDirDomTxt2.setText("");
        ICDirCobroTxt2.setText("");
        ICNitTxt2.setText("");
        ICTelefonoCasTxt2.setText("");
        ICTelOficinaTxt2.setText("");
        ICTelCelTxt2.setText("");
    }//GEN-LAST:event_ICLimpiarbtnActionPerformed

    private void ICAceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICAceptarBtnActionPerformed

        if(ICNombre1Txt2.getText().equals("") || ICApellido1Txt2.getText().equals("") || ICFNacTxt2.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Por favor rellene los siguientes campos:\n- 1er. Nombre.\n- 1er Apellido.\n- Fecha de nacimiento.");
        }else{
        
        Id_Cod Cliente =new Id_Cod();
        Ingresos Clientes = new Ingresos();
        Clientes.ingresoClt(Cliente.cod(),ICComboBox3.getSelectedItem().toString());
        ICApellido1Txt2.setText("");
        ICApellido2Txt2.setText("");
        ICApellidoCasTxt2.setText("");
        ICNombre1Txt2.setText("");
        ICNombre2Txt2.setText("");
        ICNombre3Txt2.setText("");
        ICNoDpiTxt2.setText("");
        ICFNacTxt2.setText("");
        ICEdadTxt2.setText("");
        ICProfesionTxt2.setText("");
        ICDirDomTxt2.setText("");
        ICDirCobroTxt2.setText("");
        ICNitTxt2.setText("");
        ICTelefonoCasTxt2.setText("");
        ICTelOficinaTxt2.setText("");
        ICTelCelTxt2.setText("");
        consulta.mostrar_tabla1();
        }
    }//GEN-LAST:event_ICAceptarBtnActionPerformed

    private void ICNoDpiTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICNoDpiTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ICNoDpiTxt2ActionPerformed

    private void IngresosMenu2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresosMenu2BtnActionPerformed
         CLIENTES.setSelectedIndex(1);
         ICAceptarBtn4.setEnabled(true);
         ICAceptarBtn5.setEnabled(false);
    }//GEN-LAST:event_IngresosMenu2BtnActionPerformed

    private void EliminarMenu2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMenu2BtnActionPerformed
         CLIENTES.setSelectedIndex(2);
    }//GEN-LAST:event_EliminarMenu2BtnActionPerformed

    private void ConsultaMenu2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMenu2BtnActionPerformed
       CLIENTES.setSelectedIndex(2);
    }//GEN-LAST:event_ConsultaMenu2BtnActionPerformed

    private void ModificacionMenu2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificacionMenu2BtnActionPerformed
       CLIENTES.setSelectedIndex(2);
    }//GEN-LAST:event_ModificacionMenu2BtnActionPerformed

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        this.setSize(200,40);
       
    }//GEN-LAST:event_formInternalFrameIconified

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        this.setSize(1517, 895);
    }//GEN-LAST:event_formInternalFrameDeiconified
    Consultas consulta = new Consultas();
    Busquedas src = new Busquedas();
 
    Eliminar del =new Eliminar();
    Cliente cl = new Cliente();
    conexionBD con = new conexionBD();
    Connection cn = con.conexion();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CLIENTES;
    private javax.swing.JPanel C_CLIENTES1;
    private javax.swing.JPanel C_CLIENTES2;
    private javax.swing.JTextField Cclt1BusquedaTxt;
    public static javax.swing.JComboBox<String> Cclt1ComboBox;
    private javax.swing.JButton Cclt2SalirBtn;
    private javax.swing.JButton CcltBuscarBtn;
    private javax.swing.JButton CcltEliminarBtn;
    private javax.swing.JButton CcltLimpiarBtn;
    private javax.swing.JButton CcltModificarBtn;
    private javax.swing.JButton CcltSalirBtn;
    private javax.swing.JButton ConsultaMenu2Btn;
    private javax.swing.JButton EliminarMenu2Btn;
    private javax.swing.JButton ICAceptarBtn4;
    private javax.swing.JButton ICAceptarBtn5;
    public static javax.swing.JTextField ICApellido1Txt2;
    public static final javax.swing.JTextField ICApellido2Txt2 = new javax.swing.JTextField();
    public static javax.swing.JTextField ICApellidoCasTxt2;
    public static javax.swing.JComboBox<String> ICComboBox3;
    public static javax.swing.JTextField ICDirCobroTxt2;
    public static javax.swing.JTextField ICDirDomTxt2;
    public static javax.swing.JTextField ICEdadTxt2;
    public static javax.swing.JTextField ICFNacTxt2;
    private javax.swing.JButton ICLimpiarbtn2;
    public static javax.swing.JTextField ICNitTxt2;
    public static javax.swing.JTextField ICNoDpiTxt2;
    public static javax.swing.JTextField ICNombre1Txt2;
    public static javax.swing.JTextField ICNombre2Txt2;
    public static javax.swing.JTextField ICNombre3Txt2;
    public static javax.swing.JTextField ICProfesionTxt2;
    private javax.swing.JButton ICSalirBtn;
    public static javax.swing.JTextField ICTelCelTxt2;
    public static javax.swing.JTextField ICTelOficinaTxt2;
    public static javax.swing.JTextField ICTelefonoCasTxt2;
    private javax.swing.JPanel I_CLIENTES2;
    private javax.swing.JButton IngresosMenu2Btn;
    private javax.swing.JPanel MENU2;
    private javax.swing.JButton ModificacionMenu2Btn;
    public static javax.swing.JTable TblCC1;
    public static javax.swing.JTable TblCC2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

  
}
