/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manejadora;
import Base_de_Datos.conexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
public class cumple extends javax.swing.JInternalFrame {
    
    conexionBD con = new conexionBD();
    Connection cn = con.conexion();

    public cumple() {
        initComponents();
        cumpleClientes();
    }
    
    void cumpleClientes()
    {
        //seleccionaremos datos de la base de datos
        String sql ="SELECT * FROM  tbl_clientes";
        String datos[] = new String[18];
       Statement st;
       //vamos a dibujar tabla de cumpleaños
       DefaultTableModel alertaFechas = new DefaultTableModel();
       alertaFechas.addColumn("Nombre");
       alertaFechas.addColumn("Apellido");
       alertaFechas.addColumn("Fecha");
       alertaFechas.addColumn("Estado");
       tablaCumple.setModel(alertaFechas);
       int contRow = 0;
       
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
             datos[4]= rs.getString(5);
             datos[1]= rs.getString(2);
             datos[9]= rs.getString(10);
             String auxNombre = datos[4];
             String auxApellido = datos[1];             
             String auxFecha= datos[9];
             
             char aux1 = auxFecha.charAt(0);
             char aux2 = auxFecha.charAt(1);
             char aux3 = auxFecha.charAt(2);
             char aux4 = auxFecha.charAt(3);
             char aux6 = auxFecha.charAt(5);
             char aux7 = auxFecha.charAt(6);
             char aux9 = auxFecha.charAt(8);
             char aux10 = auxFecha.charAt(9);
             String auxAux = (""+aux9+aux10+"/"+aux6+aux7+"/"+aux1+aux2+aux3+aux4); 
             
            DateTimeFormatter date1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate bornDate = LocalDate.parse(auxAux, date1);
            LocalDate todaysDate = LocalDate.now();   
            int dias;
            dias = todaysDate.getDayOfYear() - bornDate.getDayOfYear(); //hoy - fecha.nac                

            if (dias >=-5 && dias <0)
            {                    
                    String estadoFecha = "Proximo a Cumplir Años";
                    alertaFechas.insertRow(contRow, new Object[]{});
                    alertaFechas.setValueAt(auxNombre, contRow, 0);
                    alertaFechas.setValueAt(auxApellido, contRow, 1);
                    alertaFechas.setValueAt(auxFecha, contRow, 2);
                    alertaFechas.setValueAt(estadoFecha, contRow, 3);
                    contRow++;
            }
            else if (dias <=5 && dias >0)
            {
                    //System.out.println("Faltan "+dias +" dias para el cumpleaños de un cliente");
                    String estadoFecha = "Ya Cumplio Años";
                    alertaFechas.insertRow(contRow, new Object[]{});
                    alertaFechas.setValueAt(auxNombre, contRow, 0);
                    alertaFechas.setValueAt(auxApellido, contRow, 1);
                    alertaFechas.setValueAt(auxFecha, contRow, 2);
                    alertaFechas.setValueAt(estadoFecha, contRow, 3);
                    contRow++;
            }
            else if(dias == 0)
            {
                String estadoFecha = "Hoy Cumple Años";
                    alertaFechas.insertRow(contRow, new Object[]{});
                    alertaFechas.setValueAt(auxNombre, contRow, 0);
                    alertaFechas.setValueAt(auxApellido, contRow, 1);
                    alertaFechas.setValueAt(auxFecha, contRow, 2);
                    alertaFechas.setValueAt(estadoFecha, contRow, 3);
                    contRow++;
            }                
            }
            tablaCumple.setModel(alertaFechas);
        } catch (SQLException ex) {
            System.out.println("Error:"+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCumple = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("CUMPLEAÑOS");
        setMaximumSize(new java.awt.Dimension(692, 506));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        tablaCumple.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        tablaCumple.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCumple);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proximos Cumpleaños");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        this.setSize(692, 506);
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        this.setSize(200,40);
    }//GEN-LAST:event_formInternalFrameIconified


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCumple;
    // End of variables declaration//GEN-END:variables
}
