/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manejadora;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.ImageIcon;


/**
 *
 * @author gganp
 */
public class PRINCIPAL extends javax.swing.JFrame {

public  static int tipo;
    public PRINCIPAL() {
      
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/ICONS/logo.png")).getImage());
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/ICONS/DESK.jpg"));
               fondo.setIcon(uno);
       
    
      
  
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DESK = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        MENU = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DESK.setBackground(new java.awt.Color(204, 255, 255));
        DESK.setOpaque(false);

        javax.swing.GroupLayout DESKLayout = new javax.swing.GroupLayout(DESK);
        DESK.setLayout(DESKLayout);
        DESKLayout.setHorizontalGroup(
            DESKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1204, Short.MAX_VALUE)
        );
        DESKLayout.setVerticalGroup(
            DESKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        MENU.setBackground(new java.awt.Color(204, 204, 204));
        MENU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MENU.setForeground(new java.awt.Color(0, 0, 0));
        MENU.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        MENU.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenu1.setBackground(java.awt.Color.darkGray);
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("AYASEG");
        jMenu1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/reunion (1).png"))); // NOI18N
        jMenuItem1.setText("CLIENTES");
        jMenuItem1.setFocusPainted(true);
        jMenuItem1.setFocusable(true);
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem1.setIconTextGap(0);
        jMenuItem1.setInheritsPopupMenu(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(java.awt.Color.darkGray);
        jMenuItem2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/coche (2).png"))); // NOI18N
        jMenuItem2.setText("VEHICULOS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setBackground(java.awt.Color.darkGray);
        jMenuItem3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/hospital (1).png"))); // NOI18N
        jMenuItem3.setText("GASTOS MEDICOS");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setBackground(java.awt.Color.darkGray);
        jMenuItem4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/favorito.png"))); // NOI18N
        jMenuItem4.setText("SEG. VIDA");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setBackground(java.awt.Color.darkGray);
        jMenuItem5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/maquinaria (1).png"))); // NOI18N
        jMenuItem5.setText("EQUIPO ELECTRONICO");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setBackground(java.awt.Color.darkGray);
        jMenuItem6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/moneda.png"))); // NOI18N
        jMenuItem6.setText("COBROS");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ambulancia (2).png"))); // NOI18N
        jMenuItem7.setText("ASEGURADORAS");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/paisaje-urbano (1).png"))); // NOI18N
        jMenuItem8.setText("CONTACTO");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/archivo (3).png"))); // NOI18N
        jMenuItem10.setText("REPORTES");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/estrella (2).png"))); // NOI18N
        jMenuItem11.setText("CUMPLEAÑOS");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/equipo.png"))); // NOI18N
        jMenuItem12.setText("USUARIOS");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/salida (1).png"))); // NOI18N
        jMenuItem9.setText("CERRAR SESION");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        MENU.add(jMenu1);

        setJMenuBar(MENU);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DESK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DESK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        VIDA vd = new VIDA ();
        DESK.add(vd);
        vd.show();
        vd.tipo = tipo;
         vd.setVisible(false);
        VIDA vd1 = new VIDA ();
        DESK.add(vd1);
        vd1.show();
        vd1.tipo = tipo;
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CLIENTES clt = new CLIENTES ();
        CLIENTES.tipo = PRINCIPAL.tipo;
        DESK.add(clt);
        clt.show();
        clt.setVisible(false);
        CLIENTES clt1 = new CLIENTES ();
        CLIENTES.tipo = PRINCIPAL.tipo;
        DESK.add(clt1);
        clt1.show();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       VEHICULOS vhl = new VEHICULOS();
        DESK.add(vhl);
         vhl.tipo=tipo;
        vhl.show();
         vhl.setVisible(false);
         VEHICULOS vhl1 = new VEHICULOS();
        DESK.add(vhl1);
         vhl1.tipo=tipo;
        vhl1.show();
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
   GASTOS_MEDICOS med = new GASTOS_MEDICOS();
   DESK.add(med);
   med.show();
   med.tipo= tipo;
   med.setVisible(false);
   GASTOS_MEDICOS med1 = new GASTOS_MEDICOS();
   DESK.add(med1);
   med1.show();
   med1.tipo= tipo;
     
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
   ASEGURADORA ASG = new ASEGURADORA();
   DESK.add(ASG);
   ASG.show();
   ASG.tipo=tipo;
   ASG.setVisible(false);
   ASEGURADORA ASG1 = new ASEGURADORA();
   DESK.add(ASG1);
   ASG1.show();
   ASG1.tipo=tipo;
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    CONTACTO CTO = new CONTACTO();
   DESK.add(CTO);
   CTO.show();
   CTO.tipo=tipo;
    CTO.setVisible(false);
    CONTACTO CTO1 = new CONTACTO();
   DESK.add(CTO1);
   CTO1.show();
   CTO1.tipo=tipo;
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
     EQUIPO_E EE = new EQUIPO_E();
   DESK.add(EE);
   EE.show();
   EE.tipo = tipo;
    EE.setVisible(false);
     EQUIPO_E EE1 = new EQUIPO_E();
   DESK.add(EE1);
   EE1.show();
   EE1.tipo = tipo;
   
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        COBROS cbr = new COBROS();
   DESK.add(cbr);
   cbr.show();
   cbr.tipo =tipo;
   cbr.setVisible(false);
    COBROS cbr1 = new COBROS();
   DESK.add(cbr1);
   cbr1.show();
   cbr1.tipo =tipo;
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      LogIn l= new LogIn();
        this.setVisible(false);
        l.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Reportes rs = new Reportes();
        DESK.add(rs);
        rs.show();
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        cumple ce = new cumple();
        DESK.add(ce);
        ce.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       USUARIOS ce = new USUARIOS();
        DESK.add(ce);
        ce.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               PRINCIPAL ventana= new PRINCIPAL();
               ventana.setExtendedState(MAXIMIZED_BOTH);
              
               ventana.setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DESK;
    private javax.swing.JMenuBar MENU;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
